delete from taxonomy_term_data where tid =  285 ; --   אסיסטנט
delete from taxonomy_term_data where tid =   57 ; --   דיקן
delete from taxonomy_term_data where tid =  233 ; --   דיקן הפקולטה
delete from taxonomy_term_data where tid =  234 ; --   דיקן משנה
delete from taxonomy_term_data where tid =  289 ; --   חבר
delete from taxonomy_term_data where tid =  290 ; --   חוקר
delete from taxonomy_term_data where tid =  116 ; --   חניך
delete from taxonomy_term_data where tid =  292 ; --   חשב
delete from taxonomy_term_data where tid =  293 ; --   חשב הפקולטה
delete from taxonomy_term_data where tid =  294 ; --   יועץ
delete from taxonomy_term_data where tid =   66 ; --   יו''ר בית ספר להנדסה ולמדעי המחשב
delete from taxonomy_term_data where tid =  296 ; --   יו''ר החוג
delete from taxonomy_term_data where tid =  297 ; --   יו''ר המגמה
delete from taxonomy_term_data where tid =  298 ; --   יו''ר ועדת הלימודים
delete from taxonomy_term_data where tid =  184 ; --   יו''ר מכון
delete from taxonomy_term_data where tid =  300 ; --   יו''ר מסלול
delete from taxonomy_term_data where tid =  126 ; --   יו''ר תוכנית
delete from taxonomy_term_data where tid =  302 ; --   יחידת בת כספים
delete from taxonomy_term_data where tid =  249 ; --   כח אדם אקדמי
delete from taxonomy_term_data where tid =   75 ; --   מורה
delete from taxonomy_term_data where tid =   76 ; --   מזכירה
delete from taxonomy_term_data where tid =  131 ; --   מזכירה בכירה
delete from taxonomy_term_data where tid =  307 ; --   מזכירה לענייני הוראה
delete from taxonomy_term_data where tid =  308 ; --   מזכירה לענייני תלמידים
delete from taxonomy_term_data where tid =  309 ; --   מזכיר הפקולטה
delete from taxonomy_term_data where tid =  310 ; --   מזכיר לענייני הוראה ולתמידים
delete from taxonomy_term_data where tid =  311 ; --   מזכיר מכון
delete from taxonomy_term_data where tid =  197 ; --   מזכירת דיקן משנה
delete from taxonomy_term_data where tid =  313 ; --   מזכירת התוכנית
delete from taxonomy_term_data where tid =   85 ; --   מזכירת חוג
delete from taxonomy_term_data where tid =  140 ; --   מזכירת כח אדם
delete from taxonomy_term_data where tid =  316 ; --   מינהלן הוראה ותלמידים
delete from taxonomy_term_data where tid =  142 ; --   מנהל יחידה לננוייצור
delete from taxonomy_term_data where tid =   89 ; --   מנהל כוח אדם-פקולטה
delete from taxonomy_term_data where tid =  319 ; --   מנהל/ת אדמיניסטרטיבי
delete from taxonomy_term_data where tid =  145 ; --   מנהלת יחידה לננואפיון
delete from taxonomy_term_data where tid =  321 ; --   מנהלת יחידת בת כספים
delete from taxonomy_term_data where tid =  268 ; --   מנהלת מחלקת כח אדם פקולטה
delete from taxonomy_term_data where tid =  323 ; --   מתאמת מחשוב-פקולטה
delete from taxonomy_term_data where tid =  324 ; --   מתאמת מיחשוב
delete from taxonomy_term_data where tid =  210 ; --   מתרגל
delete from taxonomy_term_data where tid =  326 ; --   סגן דיקן- הוראה
delete from taxonomy_term_data where tid =  273 ; --   סגן דיקן- מחקר
delete from taxonomy_term_data where tid =  328 ; --   עוזר דיקן
delete from taxonomy_term_data where tid =  154 ; --   עוזר דיקן הפקולטה
delete from taxonomy_term_data where tid =  330 ; --   עוזר דיקן למינויים ולהעלאות
delete from taxonomy_term_data where tid =  331 ; --   עוזר מינהל יחידת שירות
delete from taxonomy_term_data where tid =  157 ; --   עוזרת לדיווח כח אדם
delete from taxonomy_term_data where tid =  279 ; --   עוזרת לחשב הפקולטה
delete from taxonomy_term_data where tid =  159 ; --   עוזרת למתאמת המחשוב
delete from taxonomy_term_data where tid =  106 ; --   עוזר/ת מינהל
delete from taxonomy_term_data where tid =  281 ; --   עוזר/ת מינהל
delete from taxonomy_term_data where tid =  167 ; --   רכזי שטחי הוראה-בניין לוי
delete from taxonomy_term_data where tid =  282 ; --   רכזי שטחי הוראה-בניין לוי
delete from taxonomy_term_data where tid =  339 ; --   רכזת בוגר 
delete from taxonomy_term_data where tid =  108 ; --   רכזת בוגר 
delete from taxonomy_term_data where tid =  340 ; --   שירותי שכפול- פקולטה
delete from taxonomy_term_data where tid =  284 ; --   שירותי שכפול- פקולטה
